# Generated by Django 4.2.1 on 2023-09-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('born', models.IntegerField()),
                ('education', models.IntegerField()),
                ('fields', models.IntegerField()),
                ('location', models.IntegerField()),
                ('region', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('language', models.IntegerField()),
                ('accessibility', models.IntegerField()),
                ('hobbies', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
