# Generated by Django 4.2.1 on 2023-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_questionnaire_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
